-- Localized descriptions for all equipment items across all supported languages

-- Spanish (es-419)
UPDATE equipment_translations SET description = 'La Hario V60 es una cafetera de goteo clásica conocida por su forma cónica y un gran orificio único, lo que permite una taza de café limpia y con notas resaltadas.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'V60');
UPDATE equipment_translations SET description = 'Diseñada por un químico, la Chemex utiliza filtros de papel gruesos para producir una bebida notablemente clara y sin sedimentos, resaltando una acidez brillante.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Chemex');
UPDATE equipment_translations SET description = 'Una cafetera versátil y portátil que utiliza presión para extraer sabores intensos. Es famosa por su durabilidad y la comunidad del ''método invertido''.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Aeropress');
UPDATE equipment_translations SET description = 'Una cafetera de inmersión total que utiliza un filtro de malla metálica, lo que resulta en una taza con mucho cuerpo, aceites ricos y una sensación texturizada.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'French Press');
UPDATE equipment_translations SET description = 'La base de muchas bebidas de café, el espresso se prepara forzando agua caliente a través de café finamente molido a alta presión.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Espresso');
UPDATE equipment_translations SET description = 'Una cafetera de estufa que produce un café fuerte, similar al espresso, utilizando presión de vapor. Un elemento básico en muchos hogares italianos.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Moka Pot');
UPDATE equipment_translations SET description = 'Una cafetera de vacío que combina la inmersión total con el filtrado de tela, produciendo una taza muy limpia y caliente con un toque teatral.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Syphon');
UPDATE equipment_translations SET description = 'Un método que consiste en remojar granos gruesos en agua fría durante 12 a 24 horas, lo que resulta en un concentrado de baja acidez y dulzura natural.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Cold Brew');
UPDATE equipment_translations SET description = 'Un Brik (también conocido como Cezve) es una pequeña jarra de mango largo con un labio vertedor, utilizada tradicionalmente para preparar café turco. Su diseño es ideal para crear la espuma característica.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Brik');
UPDATE equipment_translations SET description = 'Una cafetera de goteo de fondo plano con tres orificios pequeños, que proporciona una extracción más uniforme y un perfil más dulce y equilibrado que la V60.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Kalita Wave');
UPDATE equipment_translations SET description = 'Combina la preparación por inmersión con un mecanismo de liberación del filtro, brindando el cuerpo de una prensa francesa con la claridad de un goteo.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Clever Dripper');
UPDATE equipment_translations SET description = 'Una herramienta manual para moler granos de café. Perfecta para viajar y brindar una conexión táctil con tu preparación diaria.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Hand Grinder');
UPDATE equipment_translations SET description = 'Ofrece velocidad y consistencia para tu molienda diaria, con ajustes configurables para todo, desde espresso hasta cold brew.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Electric Grinder');
UPDATE equipment_translations SET description = 'Calienta el agua rápidamente a la temperatura deseada, esencial para una preparación constante y conveniente.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Electric Kettle');
UPDATE equipment_translations SET description = 'Proporciona un control de precisión sobre el flujo y la ubicación del agua, lo cual es crucial para lograr una extracción uniforme en los métodos de goteo.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Gooseneck Kettle');
UPDATE equipment_translations SET description = 'Garantiza la precisión al medir el café y el agua por peso en lugar de volumen, la clave para una excelencia de preparación repetible.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Digital Scale');
UPDATE equipment_translations SET description = 'Una herramienta de preparación tradicional que utiliza un filtro textil (a menudo franela) que permite que pasen más aceites que el papel, lo que da como resultado un cuerpo rico y aterciopelado.' WHERE language_code = 'es-419' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Cloth Filter');

-- Portuguese (pt-BR)
UPDATE equipment_translations SET description = 'A Hario V60 é uma cafeteira de filtragem clássica conhecida por sua forma cônica e um único orifício grande, permitindo uma xícara de café limpa e com notas ressaltadas.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'V60');
UPDATE equipment_translations SET description = 'Projetada por um químico, a Chemex usa filtros de papel grossos para produzir uma bebida notavelmente clara e sem sedimentos, destacando a acidez brilhante.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Chemex');
UPDATE equipment_translations SET description = 'Uma cafeteira versátil e portátil que usa pressão para extrair sabores ricos. É famosa por sua durabilidade e pela comunidade do ''método invertido''.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Aeropress');
UPDATE equipment_translations SET description = 'Uma cafeteira de imersão total que usa um filtro de malha metálica, resultando em uma xícara encorpada, com óleos ricos e uma sensação texturizada.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'French Press');
UPDATE equipment_translations SET description = 'A base de muitas bebidas de café, o espresso é preparado forçando água quente através de café finamente moído sob alta pressão.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Espresso');
UPDATE equipment_translations SET description = 'Uma cafeteira de fogão que produz um café forte, semelhante ao espresso, usando pressão de vapor. Um item essencial em muitos lares italianos.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Moka Pot');
UPDATE equipment_translations SET description = 'Uma cafeteira a vácuo que combina imersão total e filtragem de pano, produzindo uma xícara muito limpa e quente com um toque teatral.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Syphon');
UPDATE equipment_translations SET description = 'Um método que envolve a imersão de grãos grossos em água fria por 12 a 24 horas, resultando em um concentrado de baixa acidez e naturalmente doce.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Cold Brew');
UPDATE equipment_translations SET description = 'Um Brik (também conhecido como Cezve) é um pequeno pote de cabo longo com um bico vertedor, tradicionalmente usado para fazer café turco. Seu design é ideal para criar a espuma característica.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Brik');
UPDATE equipment_translations SET description = 'Uma cafeteira de filtragem de fundo plano com três pequenos orifícios, proporcionando uma extração mais uniforme e um perfil mais doce e equilibrado que a V60.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Kalita Wave');
UPDATE equipment_translations SET description = 'Combina o preparo por imersão com um mecanismo de liberação do filtro, oferecendo o corpo de uma prensa francesa com a clareza de um filtrado.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Clever Dripper');
UPDATE equipment_translations SET description = 'Uma ferramenta manual para moer grãos de café. Perfeita para viagens e para proporcionar uma conexão tátil com o seu preparo diário.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Hand Grinder');
UPDATE equipment_translations SET description = 'Oferece velocidade e consistência para sua moagem diária, com configurações ajustáveis para tudo, desde espresso até cold brew.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Electric Grinder');
UPDATE equipment_translations SET description = 'Aquece a água rapidamente até a temperatura desejada, essencial para um preparo consistente e conveniência.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Electric Kettle');
UPDATE equipment_translations SET description = 'Fornece controle de precisão sobre o fluxo e o posicionamento da água, o que é crucial para alcançar uma extração uniforme em métodos de filtragem.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Gooseneck Kettle');
UPDATE equipment_translations SET description = 'Garante precisão ao medir café e água por peso, em vez de volume, a chave para uma excelência de preparo repetível.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Digital Scale');
UPDATE equipment_translations SET description = 'Uma ferramenta de preparo tradicional que utiliza um filtro têxtil (geralmente flanela) que permite a passagem de mais óleos do que o papel, resultando em um corpo rico e aveludado.' WHERE language_code = 'pt-BR' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Cloth Filter');

-- Russian (ru)
UPDATE equipment_translations SET description = 'Hario V60 — классическая воронка для пуровера, известная своей конической формой и большим отверстием, что позволяет получить чистую чашку кофе с яркими вкусовыми акцентами.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'V60');
UPDATE equipment_translations SET description = 'Разработанная химиком, Кемекс использует толстые бумажные фильтры для получения удивительно прозрачного кофе без осадка, подчеркивая яркую кислотность.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Chemex');
UPDATE equipment_translations SET description = 'Универсальное и портативное устройство, использующее давление для экстракции насыщенного вкуса. Известно своей долговечностью и популярностью ''инвертного метода''.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Aeropress');
UPDATE equipment_translations SET description = 'Устройство для иммерсионного заваривания с металлическим сетчатым фильтром, в результате чего получается плотный кофе с богатыми маслами и текстурным вкусом.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'French Press');
UPDATE equipment_translations SET description = 'Основа многих кофейных напитков, эспрессо готовится путем пропускания горячей воды через мелко смолотый кофе под высоким давлением.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Espresso');
UPDATE equipment_translations SET description = 'Гейзерная кофеварка для плиты, производящая крепкий кофе, похожий на эспрессо, под давлением пара. Популярный атрибут во многих итальянских домах.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Moka Pot');
UPDATE equipment_translations SET description = 'Вакуумная кофеварка, сочетающая иммерсию и тканевую фильтрацию, позволяет приготовить очень чистый и горячий кофе с элементами театрального шоу.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Syphon');
UPDATE equipment_translations SET description = 'Метод, включающий замачивание кофе грубого помола в холодной воде на 12–24 часа, в результате чего получается концентрат с низкой кислотностью и естественной сладостью.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Cold Brew');
UPDATE equipment_translations SET description = 'Брик (также известный как джезва или турка) — это небольшой сосуд с длинной ручкой и носиком, традиционно используемый для приготовления кофе по-турецки. Дизайн идеален для создания характерной пенки.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Brik');
UPDATE equipment_translations SET description = 'Воронка с плоским дном и тремя небольшими отверстиями, обеспечивающая более равномерную экстракцию и более сладкий, сбалансированный профиль, чем V60.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Kalita Wave');
UPDATE equipment_translations SET description = 'Сочетает иммерсионное заваривание с механизмом выпуска через фильтр, давая плотность френч-пресса и чистоту пуровера.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Clever Dripper');
UPDATE equipment_translations SET description = 'Ручной инструмент для помола кофейных зерен. Идеален для путешествий и обеспечивает тактильную связь с процессом приготовления кофе.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Hand Grinder');
UPDATE equipment_translations SET description = 'Обеспечивает скорость и стабильность помола с регулируемыми настройками для всего: от эспрессо до колд-брю.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Electric Grinder');
UPDATE equipment_translations SET description = 'Быстро нагревает воду до нужной температуры, что необходимо для стабильного заваривания и удобства.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Electric Kettle');
UPDATE equipment_translations SET description = 'Обеспечивает точный контроль над потоком и направлением воды, что критически важно для равномерной экстракции в методах пуровера.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Gooseneck Kettle');
UPDATE equipment_translations SET description = 'Обеспечивает точность, измеряя кофе и воду по весу, а не по объему — ключ к стабильно превосходному результату.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Digital Scale');
UPDATE equipment_translations SET description = 'Традиционный инструмент для заваривания с использованием тканевого фильтра (часто фланелевого), который пропускает больше масел, чем бумажный, создавая насыщенное, бархатистое тело.' WHERE language_code = 'ru' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Cloth Filter');

-- Georgian (ka)
UPDATE equipment_translations SET description = 'Hario V60 არის კლასიკური დასასხმელი (pour-over) მადუღარა, რომელიც ცნობილია თავისი კონუსური ფორმით და დიდი ნახვრეტით, რაც სუფთა და ნათელი არომატის ყავას იძლევა.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'V60');
UPDATE equipment_translations SET description = 'ქიმიკოსის მიერ შექმნილი Chemex იყენებს სქელ ქაღალდის ფილტრებს საოცრად გამჭვირვალე და ნალექისგან თავისუფალი ყავის მოსამზადებლად, რაც ხაზს უსვამს მის სასიამოვნო მჟავიანობას.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Chemex');
UPDATE equipment_translations SET description = 'მრავალმხრივი და პორტატული მოწყობილობა, რომელიც იყენებს წნევას მდიდარი გემოს ექსტრაქციისთვის. ცნობილია თავისი გამძლეობით და ''ინვერსიული მეთოდის'' მოყვარულთა საზოგადოებით.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Aeropress');
UPDATE equipment_translations SET description = 'სრული იმერსიის მოწყობილობა, რომელიც იყენებს ლითონის ბადისებრ ფილტრს. შედეგად მიიღება სქელი ყავა მდიდარი ზეთებით და სასიამოვნო ტექსტურით.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'French Press');
UPDATE equipment_translations SET description = 'ბევრი ყავის სასმელის საფუძველი. ესპრესო მზადდება მაღალი წნევით ცხელი წყლის გატარებით წმინდად დაფქულ ყავაში.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Espresso');
UPDATE equipment_translations SET description = 'ქურაზე დასადგამი მადუღარა, რომელიც ორთქლის წნევის გამოყენებით ამზადებს ძლიერ, ესპრესოს მსგავს ყავას. იტალიური ოჯახების განუყოფელი ნაწილი.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Moka Pot');
UPDATE equipment_translations SET description = 'ვაკუუმური მადუღარა, რომელიც აერთიანებს სრულ იმერსიას და ნაჭრის ფილტრაციას. ამზადებს ძალიან სუფთა და ცხელ ყავას თეატრალური ეფექტით.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Syphon');
UPDATE equipment_translations SET description = 'მეთოდი, რომელიც გულისხმობს მსხვილად დაფქული ყავის ცივ წყალში დაყენებას 12-24 საათის განმავლობაში. შედეგად მიიღება დაბალი მჟავიანობის და ბუნებრივად ტკბილი კონცენტრატი.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Cold Brew');
UPDATE equipment_translations SET description = 'ბრიკი (ასევე ცნობილი როგორც ჯეზვე ან თურქული ყავის მადუღარა) არის პატარა, გრძელსახელურიანი ჭურჭელი, რომელიც ტრადიციულად გამოიყენება თურქული ყავის მოსადუღებლად. იდეალურია დამახასიათებელი ქაფის შესაქმნელად.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Brik');
UPDATE equipment_translations SET description = 'ბრტყელძირიანი მადუღარა სამი პატარა ნახვრეტით. უზრუნველყოფს უფრო თანაბარ ექსტრაქციას და უფრო ტკბილ, დაბალანსებულ გემოს, ვიდრე V60.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Kalita Wave');
UPDATE equipment_translations SET description = 'აერთიანებს იმერსიულ მოხარშვას და ფილტრის გამოშვების მექანიზმს. იძლევა ფრენჩ პრესის სხეულს და დასასხმელი მეთოდის სისუფთავეს.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Clever Dripper');
UPDATE equipment_translations SET description = 'ყავის მარცვლების დასაფქვავი ხელის ხელსაწყო. იდეალურია მოგზაურობისთვის და ყავის მომზადების პროცესთან ტაქტილური კავშირისთვის.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Hand Grinder');
UPDATE equipment_translations SET description = 'უზრუნველყოფს თქვენი ყოველდღიური დაფქვის სისწრაფეს და სტაბილურობას. აქვს რეგულირებადი პარამეტრები ყველაფრისთვის: ესპრესოდან ქოლდ ბრიუმდე.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Electric Grinder');
UPDATE equipment_translations SET description = 'სწრაფად აცხელებს წყალს სასურველ ტემპერატურამდე. აუცილებელია სტაბილური მომზადებისთვის და მოხერხებულობისთვის.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Electric Kettle');
UPDATE equipment_translations SET description = 'უზრუნველყოფს წყლის ნაკადის და მიმართულების ზუსტ კონტროლს, რაც გადამწყვეტია თანაბარი ექსტრაქციისთვის დასასხმელი მეთოდების დროს.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Gooseneck Kettle');
UPDATE equipment_translations SET description = 'უზრუნველყოფს სიზუსტეს ყავისა და წყლის წონით გაზომვისას, რაც საუკეთესო შედეგის გამეორების გასაღებია.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Digital Scale');
UPDATE equipment_translations SET description = 'მომზადების ტრადიციული ხელსაწყო, რომელიც იყენებს ნაჭრის (ხშირად ფლანელის) ფილტრს. ის ატარებს მეტ ზეთს, ვიდრე ქაღალდი, რაც იძლევა მდიდარ და ხავერდოვან სხეულს.' WHERE language_code = 'ka' AND equipment_id IN (SELECT id FROM equipment WHERE name = 'Cloth Filter');
